name: simple_platformer
description: The Simple Platformer game.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.1.0

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  flame: 1.0.0
  flame_tiled: 1.0.0
  # tiled: 0.10.1
  # flame_audio: 2.0.4

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/tiles/
    - assets/audio/
